config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do 
  	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments,:dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts,:dependent => :destroy
  has_many :comments,:dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :destroy, :new]
  before_action :comment_params, only: [:create]
  before_action :authenticate_user!
  
  def new
  end
  def create
	@comment = @post.comments.build(comment_params)
	@comment.user = current_user
	respond_to do |format|
		if @comment.save
			format.html { redirect_to @comment, notice: 'Post was successfully created.' }
			format.js
			# ActionCable.server.broadcast "comments",
			# render(partial:'comments/comment',object: @comment)
			# flash[:notice] = 'Comment has been created'
			# format.json{ render :show, status: :created, location: @comment}
	    else
	    	format.html{render :new}
	      flash[:alert] = 'Comment has not been created'
	    end
	end
  end

  def destroy
  	@comment = @post.comments.find(params[:id])
  	@comment.destroy
  	redirect_to post_path(@post)
  end

	private
    def set_post
	    @post = Post.find(params[:post_id])
	end

	def comment_params
	    params.require(:comment).permit(:id,:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_post, only:[:show, :edit, :update, :destroy]
	def index
		@post = Post.all
	end

	def new
		@post = current_user.posts.build
	end

	def show
		@comment = @post.comments.build
		@comments = @post.comments.includes(:user)
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to post_path(@post), notice: "Success"
		else
			flash.now[:warning] = 'The post has been created!'
			render 'new'
		end
	end

	def edit 
	    unless @post.user == current_user
			flash[:alert] = "This is not your post!"
			redirect_to root_path
		end
	end

	def update
		unless @post.user == current_user
			flash[:danger] = "This is not your post!"
			redirect_to root_path
		else
			if @post.update(post_params)
				redirect_to post_path(@post), notice: "The post has been updated!"
			else
				flash.now[:alert] = "Post has not been updated!"
				render 'edit'
			end
		end	
	end

	def destroy
    unless @post.user == current_user
      redirect_to root_path, alert: "This is not your post!"
    else
       if @article.destroy
        redirect_to root_path, notice: "Article has been deleted"
       end
    end
  end



	private
	def post_params
		params.require(:post).permit(:title, :text)
	end

	def set_post
    @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def persisted_comments(comments)
    comments.reject{ |comment| comment.new_record? }
  end
end

app/views/comments/_comment.html.erb
 	<div class="comment-body">
            <%= comment.body %> </br>
            <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.email %>
    </div>
    <% if current_user == @post.user %>
        <%= link_to 'Destroy Comment',[comment.post, comment], :confirm =>'Are you sure?', :method => :delete %>
    <% end %>
    <hr>
   
    

app/views/comments/_form.html.erb
 <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :body, 'New comment'%><br/>
      </div>
      <div class="col-md-10">
        <%= f.text_area :body, row: 20, placeholder: 'Please input your comments', class: 'form-control' %>
      </div>
  </div>

  <div class="form-group">
      <div class="actions">
        <%= f.submit 'Add Comment' %>
      </div>
  </div>

app/views/comments/create.js.erb
<% if @comment.new_record? %>
	alert("You should input your comment!");
<% else %>
	$("#comment-append").append("<%= j render @comment %>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Postboard</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top">
      <div class="container">
        <nav>

          <ul class="nav navbar-nav navbar-right">

           <%= link_to yield(:email),
                    root_url(email: yield(:email)) \
                      unless user_session.nil? %>
            <li><%= link_to "All posts", root_url %></li>

			 <% if current_user %>
			   <li><%= link_to "New post", new_post_path %></li>
			     <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %> </li>
			  <li>  <%= link_to('修改密碼', edit_registration_path(:user)) %></li>
        
			  <% else %>
			   <li> <%= link_to('註冊', new_registration_path(:user)) %></li>
			   <li> <%= link_to('登入', new_session_path(:user)) %></li>
			  
			  <% end %>


          </ul>
        </nav>
      </div>
    </header>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>

 <div class="wrap_footer">
        <div class="group footer_top">
            <div class="footer first">
                <h2>About Me</h2>
                <p>I’m Lia , this is my first rail's project.</p>
            </div>
            <div class="footer second">
                <h2>Phone</h2>
                <p>please don't call me~</br>lialilingchen@gmail.com</p>
            </div>
            <div class="footer third">
                <h2>Address</h2>
                <p>Washington, USA </br>6036 Richmond hwy., </br>Alexandria, VA, 2230</p>
            </div>
            <div class="footer fourth">
                <h2>Subscribe to My Newsletter</h2>
                <form action="">
                    <input type="text" placeholder="E-mail...">
                    <button>Send</button>
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="group footer_bottom">
            <p>Lia Chen© 2017. <a href="#"><em>Privacy Policy</em></a></p>
        </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form">
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :text %>
  <%= f.text_area :text %><br>
<br>
  <%= f.submit "Submit", class: "btn btn-primary btn-lg"%>
<% end %>
</div>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>

<h1>Edit Post</h1>
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<% provide(:username, @username) %>
<% if params[:name].nil? %>
  <h1>All Posts</h1>
  <% provide(:title, "All Posts") %>
<% else %>
  <h1>My Posts</h1>
  <% provide(:title, "My Posts") %>
<% end %>



<div class="row">
<% @post.each do |post| %>
    <div class="col-md-4">
      <h2><%= post.title %></h2>
      <p><%= post.text %></p>
      <em>---- by 
        <% if user_session.nil? %>
          <%= "********" %> 
          <%= link_to "(Sign in to see)", signin_path %>
        <% else %>
          <%= "#{post.user.email}" %>
        <% end %>
      </em>
    
      <%= link_to 'See comments', post_path(post) %><br>
    </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<h1>New Post</h1>
<%= render partial: 'form' %>

app/views/posts/show.html.erb
<p class="notice"><%= notice %></p>

<div class="row">
    <div class="col-md-4">
      <h2><%= @post.title %></h2>
      <p><%= @post.text %></p>
            <em>---- by 
                <% if user_session.nil? %>
                  <%= "********" %> 
                  <%= link_to "(Sign in to see)", signin_path %>
                  Created <%= time_ago_in_words(@post.created_at) %> ago
                <% else %>
                 
                  Created <%= time_ago_in_words(@post.created_at) %> ago by <%= "#{@post.user.email}" %>
                <% end %>
                <% if current_user == @post.user %>
                    <%= link_to 'Edit Post', edit_post_path(@post) %> 
                <% end %>
                <%= link_to 'Back to Posts', posts_path %> 
            </em>
    </div>
</div>



<div class="comment-content">
<div class= "comment-content">
    <div class="col-md-10">
     <h2>Comments</h2>     
      <% if @post.comments.any?%>
          <div id="comments">
            <%= render @comments %> 
            <div id="comment-append"></div>
          </div>       
      <% else %>
        <h3>There is no any comment.</h3>
      <% end %>
    </div>
</div>
 
  

  <%= simple_form_for [@post, @comment], remote: true do |f| %>
      <div class="form-group">
        <%= f.input :body, input_html: { :class => "form-control" }, :style => "background-color: transparent" %>
      </div>
      <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>
    <% end %>
  
  <br />
</div>